### ISSUE TITLE
How to reverse list workspace?

### ISSUE THREAD

**Issue by adibpwd** [lukaszjablonski/xfdashboard-lj#1]
How can we reverse the order of the workspace list from 1 - 5 to 5 - 1 ?

![image](https://github.com/lukaszjablonski/xfdashboard-lj/assets/54851209/d9a15329-9ca0-4bfc-a414-c042de42e4d2)

**Comment by adibpwd** [comment]
And perhaps I would like to change the workspace list to:

At the top
Adding border radius
Spacing between workspaces
Decreasing the size

**Comment by lukaszjablonski** [comment]
> How can we reverse the order of the workspace list from 1 - 5 to 5 - 1 ?

This is not theme related question as far as I remember. It's realised by [xfdashboard](https://docs.xfce.org/apps/xfdashboard/) independent of selected theme (if doable at all).

> And perhaps I would like to change the workspace list to:
> 
> At the top
> Adding border radius
> Spacing between workspaces
> Decreasing the size

This is all controlled by the following files: [`xfdashboard.css`](https://github.com/lukaszjablonski/xfdashboard-lj/blob/master/xfdashboard-1.0/xfdashboard.css), [`xfdashboard-lj.css`](https://github.com/lukaszjablonski/xfdashboard-lj/blob/master/xfdashboard-1.0/xfdashboard-lj.css), [`xfdashboard.xml`](https://github.com/lukaszjablonski/xfdashboard-lj/blob/master/xfdashboard-1.0/xfdashboard.xml), and [`xfdashboard-secondary.xml`](https://github.com/lukaszjablonski/xfdashboard-lj/blob/master/xfdashboard-1.0/xfdashboard-secondary.xml).

In more details, to get workspaces: "at the top", section `XfdashboardWorkspaceSelector` of [`xfdashboard.xml`](https://github.com/lukaszjablonski/xfdashboard-lj/blob/master/xfdashboard-1.0/xfdashboard.xml), and [`xfdashboard-secondary.xml`](https://github.com/lukaszjablonski/xfdashboard-lj/blob/master/xfdashboard-1.0/xfdashboard-secondary.xml) has to be moved above `XfdashboardWindowsView` as far as I remember.

On the other hand "adding border radius" and "spacing between workspaces" has to be addressed by adding/changing `corner-radius` property in `XfdashboardLiveWorkspace` and `spacing` in `XfdashboardWorkspaceSelector`, respectively, in [`xfdashboard-lj.css`](https://github.com/lukaszjablonski/xfdashboard-lj/blob/master/xfdashboard-1.0/xfdashboard-lj.css) or  [`xfdashboard.css`](https://github.com/lukaszjablonski/xfdashboard-lj/blob/master/xfdashboard-1.0/xfdashboard.css).

Finally, although I'm not sure which element is "decreasing the size" referring to, I guess it's again in one of  `*.css` files.

For further understanding of [xfdashboard](https://docs.xfce.org/apps/xfdashboard/) themes concept I suggest to check:
https://xfdashboard.froevel.de/theming.html

Generally speaking, any of these is not really an issue of the theme but part of it's design. I'm not planning to make such changes  so I'm closing this one. I believe that with above info you're on a good way to develop your own theme.
